### ISSUE TITLE
Downloading Example folder

### ISSUE THREAD

**Issue by simang5c** [CoExpNetViz/CoExpNetViz#14]
Hi, I wanted to try theCoExpNetViz plugin in Cytoscape so I was looking to download "coexpnetviz_example.tgz"  zipped file but  I couldn't download it. I think the link is not working. could you please check and help me with the same?

Thanks,
Simang

**Comment by timdiels** [comment]
Hi Simang, sorry I forgot to turn on email notifications for this repo. In case you still need them, I will be adding them to this repo.

**Comment by timdiels** [comment]
I've added them here: https://github.com/CoExpNetViz/coexpnetviz-data/blob/main/example.zip
