### ISSUE TITLE
Results not reproducible over time for larger datasets and often blank network plots

### ISSUE THREAD

**Issue by TizianaS92** [CoExpNetViz/CoExpNetViz#25]
Hello everyone,
I'm trying to use the CoExpNetViz Cytoscape plugin to individuate significant expression correlations (in a co-expression network) between a reduced number of genes of interest (9) and a larger number of them in a dataset. My first dataset aimed to individuate the correlations between 9 bait genes and 2300 potential targets, over 6 samples.

I ran into a weird behaviour... 
It seems that, if the number of genes to investigate is relatively high (>500), the results are not reproducible. 
I get a slightly different network plot every time, and, for certain datasets, no plot (only a blank screen).
 
For instance, out of 5 runs, I can obtain some, or all, slightly different correlations. The greater the number of genes to investigate, the more pronounced the differences among the attempts. I also suspect the result is truncated, especially for larger datasets,  because the significant correlations aren't as many as I would expect.
The problem only occured with a dataset of at least 500 genes, approximately. I ran this kind of test on a smaller one (477) and the results didn't vary.

Here is an example: on a dataset of 1000 genes, out of 5 runs, I get 3 different results, individuating a slight different number of target genes for each case. Pearson coefficients don't vary for the mutual genes.

https://i.ibb.co/vvn32mg/Test1.png

https://i.ibb.co/pZMxvkX/Test2.png

https://i.ibb.co/1bPK5kW/Test3.png

At first, I believed the problem could be memory-related, so I tried, as suggested in Cytoscape 3.9.1 manual, to allocate more space ([here](https://manual.cytoscape.org/en/3.9.1/Launching_Cytoscape.html), paragraphs Overall Memory Size for Cytoscape and Stack Size) but it made no difference. 
Also uninstalling and reinstalling the plugin didn't change anything, nor using a computer with a higher RAM (I have 64 GBs right now).

Has this happened to anyone? What could the issue be? Thanks in advance.

**Comment by timdiels** [comment]
Hi,

I think what you're seeing is a change in the lower and upper cutoff value across runs, which determines whether a correlation value is considered significant. These are determined from correlations between a *sample* of 800 genes of the dataset, which would explain why it seems stable for datasets with up to 800 genes. I think this could also result in cutoff values where no correlation with the baits is considered significant, i.e. an empty network/plot.

The cutoff estimation:
https://github.com/CoExpNetViz/coexpnetviz-python/blob/99be8e9ea39d2a6180f33d3ab5aeb196952441b3/coexpnetviz/_algorithm.py#L111

Cheers,

Tim
