### ISSUE TITLE
pandas.errors InvalidIndexError: Reindexing only valid with uniquely valued Index objects

### ISSUE THREAD

**Issue by dionne099** [CoExpNetViz/CoExpNetViz#26]
I would like to make a co-expression network using multiple species and their gene expression datasets. I am practicing on two species for now and this is the traceback error I keep receiving:

  File "/home/dm25256/.conda/envs/coexpnetviz6/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3721, in get_indexer
    raise InvalidIndexError(self._requires_unique_msg)
pandas. errors.InvalidIndexError: Reindexing is only valid with uniquely valued Index objects

I have checked to make sure all of my inputs are correct (no duplicate rows/ columns; the YAML file looks good). Are there any other reasons why this error arises?

**Comment by timdiels** [comment]
Hi, feel free to open an issue with the bug template so I have all the info I need to help.

**Comment by timdiels** [comment]
Oh it's already an issue
