### ISSUE TITLE
Tissue difference

### ISSUE THREAD

**Issue by lychen83** [CoExpNetViz/CoExpNetViz#8]
Hello.

I plan to use CoExpNetViz for my analysis. I have three genes, which will be used as baits to get the genes co-expressed with them.  I will get RNA-seq data.   The samples are heterogeneous (different treatment, different tissues and different developing stages).  The WGCNA suggested that 'Data heterogeneity may affect any statistical analysis, and even more so an unsupervised one such as WGCNA'. However, my purpose is not to construct co-expressed module/network.  I just want to find out the genes co-expressed with baits.  Is the heterogeneity an advantage or disadvantage. Is it negatively affect my results?

Thank you so much.

Best wishes,
Lingyun Chen

**Comment by timdiels** [comment]
Hi Linyun, sorry I missed your question, I forgot to turn on email notifications. If you still need an answer, feel free to reopen it and I'll get back to you promptly.
